### ISSUE TITLE
How do you add another language as a microservice using this structure?

### ISSUE THREAD

**Issue by rlam3** [ya-mori/python-monorepo#1]
Hi, 

I found this repo to be interesting I have a few questions:

1. How do you add another language as a microservice using this structure? 
Ex a JS FrontEnd, another Go backend service

2. How do you handle linting and commitizen with pre-commit hooks for this project?

**Comment by ya-mori** [comment]
@rlam3 
Thanks for posting the issue.

> How do you add another language as a microservice using this structure?
> Ex a JS FrontEnd, another Go backend service

This project is intended to be used only with Python.

> How do you handle linting and commitizen with pre-commit hooks for this project?

In my product, I'm using Google Cloud Build to set up triggers under specific directories.
ex) trigger1 hooks  only `projects/project-one/`
