### ISSUE TITLE
Thank you for this project!

### ISSUE THREAD

**Issue by tony** [ya-mori/python-monorepo#4]
I'm surprised more projects (e.g. poetry, pip, jupyter, ipython) don't use and encourage monorepos

Do you know any open source python projects using monorepos?

**Comment by ya-mori** [comment]
@tony 
Thanks for posting the issue.

Unfortunately, I don't know.
This project was adapted from this amazing article!
https://medium.com/opendoor-labs/our-python-monorepo-d34028f2b6fa

**Comment by tony** [comment]
Excellent and nice to look at the gradle project, @ya-mori 

I'm dabbling with something here: https://github.com/cihai/cihai/tree/monorepo, https://github.com/cihai/cihai/pull/297.  There's areas I haven't gotten to yet like composite GH actions (for reusability)

I appreciate the link to [opendoor lab's article](https://medium.com/opendoor-labs/our-python-monorepo-d34028f2b6fa), I also found them while googling.

keep me posted if you develop this more or find any more projects
